repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff (uv run)
        language: system
        entry: uv run ruff check --fix
        types: [python]

      - id: mypy-check
        name: mypy (uv run)
        language: system
        entry: uv run mypy .
        pass_filenames: false